![This is an image](Quant-Trading.jpg)

<font size="3">
Please visit our website <a href="https://www.quant-trading.co" target="_blank">quant-trading.co</a> for more tools on quantitative finance and data science.
</font>

# **RETURN AND VOLATILITY OF A PORTFOLIO**

## **Â¿How to calculate the mean return and the volatility of a portfolio?**

<font size="3"> In this notebook we will explore how to calculate the return and the volatility of a portfolio of assets. We already learnt how to calculate: <br><br><br>
    1. Cumulative returns here: <a href="https://quant-trading.co/how-to-calculate-cumulative-returns-using-python/" target="_blank">CUM RETURNS</a><br><br>
    2. Volatilities here: <a href="https://quant-trading.co/how-to-calculate-volatility/" target="_blank">VOLATILITY</a><br><br>
    3. Correlations here: <a href="https://quant-trading.co/how-to-calculate-correlation-from-financial-returns-using-python/" target="_blank">CORRELATION</a><br><br>
   
<font size="3"> Now we will learn how to use these concepts and calculate the return and the volatility of a portfolio consisting of multiple assets.     
<br><br>

In [1]:
import warnings
warnings.filterwarnings('ignore')

import yfinance as yf  #Yahoo Finance
import datetime
import pandas as pd
import numpy as np

## **Get an specific or multiple tickers**

<font size="3"> Stocks have an specific identification code. Here we show how to download the prices history for what are known as the magnificent 7 stocks for an specific time frame. remember that we show how to download data from the yahoo finance api in the following link: <a href="https://quant-trading.co/how-to-download-data-from-yahoo-finance-api/" target="_blank">YAHOO FINANCE API</a>
<br><br>

In [2]:
#ASSET
tickers_list = ['SPY', 'TLT', 'IAU', 'EMB', 'USO', 'EEM','SHV']

multiple_prices = yf.download(tickers_list,period='5y')['Adj Close']


for elem in tickers_list:    
    multiple_prices['Return '+ elem] = multiple_prices[elem]/multiple_prices[elem].shift(1) - 1
    multiple_prices['Return '+ elem].iloc[0] = 0

[*********************100%***********************]  7 of 7 completed

<font size="3"> We can have a visual inspection of the DataFrame.
<br><br>

In [3]:
multiple_prices

,EEM,EMB,IAU,SHV,SPY,TLT,USO,Return SPY,Return TLT,Return IAU,Return EMB,Return USO,Return EEM,Return SHV
Date,,,,,,,,,,,,,,
2019-03-14,37.883274,86.841774,24.820000,100.427185,259.107574,108.059601,97.760002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2019-03-15,38.436447,87.193642,24.920000,100.454437,260.387695,108.774345,97.599998,0.004940,0.006614,0.004029,0.004052,-0.001637,0.014602,0.000271
2019-03-18,38.864708,87.273628,24.959999,100.436241,261.331909,108.711815,98.480003,0.003626,-0.000575,0.001605,0.000917,0.009016,0.011142,-0.000181
2019-03-19,38.882549,87.337601,25.020000,100.463531,261.396667,108.470566,98.239998,0.000248,-0.002219,0.002404,0.000733,-0.002437,0.000459,0.000272
2019-03-20,38.945004,88.113228,25.180000,100.472626,260.609894,109.605179,100.000000,-0.003010,0.010460,0.006395,0.008881,0.017915,0.001606,0.000091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-07,40.860001,89.110001,40.830002,110.199997,514.809998,95.900002,74.230003,0.009926,-0.000938,0.005417,0.002701,-0.001480,0.006156,0.000363
2024-03-08,40.820000,89.209999,41.180000,110.209999,511.720001,95.730003,73.360001,-0.006002,-0.001773,0.008572,0.001122,-0.011720,-0.000979,0.000091
2024-03-11,40.910000,89.070000,41.250000,110.220001,511.279999,95.680000,73.620003,-0.000860,-0.000522,0.001700,-0.001569,0.003544,0.002205,0.000091
2024-03-12,41.360001,88.949997,40.810001,110.239998,516.780029,94.879997,73.349998,0.010757,-0.008361,-0.010667,-0.001347,-0.003668,0.011000,0.000181
2024-03-13,41.230000,89.040001,41.095001,110.250000,516.000000,94.419998,75.099998,-0.001509,-0.004848,0.006984,0.001012,0.023858,-0.003143,0.000091

<font size="3"> The first thing we need to do is to filter the DataFrame to just leave the returns of the assets.
<br><br>

In [4]:
multiple_returns = multiple_prices[['Return SPY','Return TLT','Return IAU','Return EMB','Return USO','Return EEM','Return SHV']]
multiple_returns

,Return SPY,Return TLT,Return IAU,Return EMB,Return USO,Return EEM,Return SHV
Date,,,,,,,
2019-03-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2019-03-15,0.004940,0.006614,0.004029,0.004052,-0.001637,0.014602,0.000271
2019-03-18,0.003626,-0.000575,0.001605,0.000917,0.009016,0.011142,-0.000181
2019-03-19,0.000248,-0.002219,0.002404,0.000733,-0.002437,0.000459,0.000272
2019-03-20,-0.003010,0.010460,0.006395,0.008881,0.017915,0.001606,0.000091
...,...,...,...,...,...,...,...
2024-03-07,0.009926,-0.000938,0.005417,0.002701,-0.001480,0.006156,0.000363
2024-03-08,-0.006002,-0.001773,0.008572,0.001122,-0.011720,-0.000979,0.000091
2024-03-11,-0.000860,-0.000522,0.001700,-0.001569,0.003544,0.002205,0.000091
2024-03-12,0.010757,-0.008361,-0.010667,-0.001347,-0.003668,0.011000,0.000181
2024-03-13,-0.001509,-0.004848,0.006984,0.001012,0.023858,-0.003143,0.000091

## **Calculate cumulative returns**

<font size="3"> Now we will run a for loop to calculate the cumulative returns for all the assets
<br><br>

In [5]:
multiple_returns2 = multiple_returns.copy()

for elem in tickers_list:    
    multiple_returns2['Cum_Return '+ elem] = (1 + multiple_returns['Return '+ elem]).cumprod() - 1

multiple_returns2

,Return SPY,Return TLT,Return IAU,Return EMB,Return USO,Return EEM,Return SHV,Cum_Return SPY,Cum_Return TLT,Cum_Return IAU,Cum_Return EMB,Cum_Return USO,Cum_Return EEM,Cum_Return SHV
Date,,,,,,,,,,,,,,
2019-03-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2019-03-15,0.004940,0.006614,0.004029,0.004052,-0.001637,0.014602,0.000271,0.004940,0.006614,0.004029,0.004052,-0.001637,0.014602,0.000271
2019-03-18,0.003626,-0.000575,0.001605,0.000917,0.009016,0.011142,-0.000181,0.008585,0.006036,0.005641,0.004973,0.007365,0.025907,0.000090
2019-03-19,0.000248,-0.002219,0.002404,0.000733,-0.002437,0.000459,0.000272,0.008835,0.003803,0.008058,0.005710,0.004910,0.026378,0.000362
2019-03-20,-0.003010,0.010460,0.006395,0.008881,0.017915,0.001606,0.000091,0.005798,0.014303,0.014504,0.014641,0.022913,0.028026,0.000452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-03-07,0.009926,-0.000938,0.005417,0.002701,-0.001480,0.006156,0.000363,0.986858,-0.112527,0.645044,0.026119,-0.240691,0.078576,0.097312
2024-03-08,-0.006002,-0.001773,0.008572,0.001122,-0.011720,-0.000979,0.000091,0.974933,-0.114100,0.659146,0.027271,-0.249591,0.077520,0.097412
2024-03-11,-0.000860,-0.000522,0.001700,-0.001569,0.003544,0.002205,0.000091,0.973234,-0.114563,0.661966,0.025658,-0.246931,0.079896,0.097512
2024-03-12,0.010757,-0.008361,-0.010667,-0.001347,-0.003668,0.011000,0.000181,0.994461,-0.121966,0.644239,0.024277,-0.249693,0.091775,0.097711
2024-03-13,-0.001509,-0.004848,0.006984,0.001012,0.023858,-0.003143,0.000091,0.991451,-0.126223,0.655721,0.025313,-0.231792,0.088343,0.097810

<font size="3"> Now we will filter the DataFrame to just leave the cumulative returns of the assets.
<br><br>

In [6]:
multiple_cum_returns = multiple_returns2[['Cum_Return SPY','Cum_Return TLT','Cum_Return IAU','Cum_Return EMB','Cum_Return USO','Cum_Return EEM','Cum_Return SHV']]
multiple_cum_returns

,Cum_Return SPY,Cum_Return TLT,Cum_Return IAU,Cum_Return EMB,Cum_Return USO,Cum_Return EEM,Cum_Return SHV
Date,,,,,,,
2019-03-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2019-03-15,0.004940,0.006614,0.004029,0.004052,-0.001637,0.014602,0.000271
2019-03-18,0.008585,0.006036,0.005641,0.004973,0.007365,0.025907,0.000090
2019-03-19,0.008835,0.003803,0.008058,0.005710,0.004910,0.026378,0.000362
2019-03-20,0.005798,0.014303,0.014504,0.014641,0.022913,0.028026,0.000452
...,...,...,...,...,...,...,...
2024-03-07,0.986858,-0.112527,0.645044,0.026119,-0.240691,0.078576,0.097312
2024-03-08,0.974933,-0.114100,0.659146,0.027271,-0.249591,0.077520,0.097412
2024-03-11,0.973234,-0.114563,0.661966,0.025658,-0.246931,0.079896,0.097512
2024-03-12,0.994461,-0.121966,0.644239,0.024277,-0.249693,0.091775,0.097711
2024-03-13,0.991451,-0.126223,0.655721,0.025313,-0.231792,0.088343,0.097810

## **Getting the cumulative return of the portfolio**

<font size="3"> The cumulative returns for each asset will be the ones we have on the final row of the DataFrame. Those numbers will show the total return of the entire period. In this case we are using a 5 year time span. Therefore, we need to raise that number to the power of 1/5 and then substract 1 to get the annualized return for each asset class.
<br><br>

In [7]:
multiple_cum_returns.iloc[-1]

Cum_Return SPY    0.991451
Cum_Return TLT   -0.126223
Cum_Return IAU    0.655721
Cum_Return EMB    0.025313
Cum_Return USO   -0.231792
Cum_Return EEM    0.088343
Cum_Return SHV    0.097810
Name: 2024-03-13 00:00:00, dtype: float64

<font size="3"> We can put those numbers into a numpy array in the following way:
<br><br>

In [8]:
portfolio_returns = np.array((1+multiple_cum_returns.iloc[-1])**(1/5)-1)
portfolio_returns

array([ 0.14771463, -0.02662514,  0.10610778,  0.00501211, -0.05137242,
        0.01707543,  0.01883877])

<font size="3"> Then, we need to define how much we hold in each asset class. That can be easily done using a numpy array as well.
<br><br>

In [9]:
asset_class_weights = np.array([0.3,0.1,0.1,0.1,0.1,0.1,0.2])
asset_class_weights

array([0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2])

<font size="3"> The portolio's return is the multiplication of the annualized return times the weight of each asset class. 
<br><br>

In [10]:
portfolio_return = portfolio_returns.dot(asset_class_weights) 
portfolio_return

0.05310191858526151

## **Getting the volatility of the portfolio**

<font size="3"> The way to calculate the volatility of the portfolio involves getting the volatilities for each asset class and also the correlation matrix of them. To get the volatilities of each asset class we need to calculate the standard deviation of the returns as follows:
<br><br>

In [11]:
multiple_returns.std()

Return SPY    0.013182
Return TLT    0.011199
Return IAU    0.009391
Return EMB    0.007924
Return USO    0.027856
Return EEM    0.014037
Return SHV    0.000186
dtype: float64

<font size="3"> The we annualized that number as we show here: <a href="https://quant-trading.co/how-to-calculate-volatility/" target="_blank">VOLATILITY</a>
<br><br>

In [12]:
portfolio_volatilities = np.array(multiple_returns.std()[0:7]*252**0.5)
portfolio_volatilities

array([0.20925049, 0.17778066, 0.14908361, 0.12579618, 0.44220752,
       0.22283229, 0.00294627])

<font size="3"> To calculate the volatility of the entire portfolio we will have to do a matrix multiplication involving: a) The vector of asset classes' variances, b) The correlation martiz, c) The vector of asset classes' variances transpose. Lets see:
<br><br>

In [13]:
portfolio_variances = portfolio_volatilities**2
portfolio_variances

array([4.37857661e-02, 3.16059641e-02, 2.22259222e-02, 1.58246794e-02,
       1.95547488e-01, 4.96542292e-02, 8.68047929e-06])

In [14]:
corr_matrix = np.array(multiple_returns.corr())
corr_matrix

array([[ 1.        , -0.18442465,  0.11477921,  0.61699675,  0.30879332,
         0.77359164, -0.06014372],
       [-0.18442465,  1.        ,  0.3126747 ,  0.35169442, -0.17248357,
        -0.14770154,  0.23398569],
       [ 0.11477921,  0.3126747 ,  1.        ,  0.31139755,  0.0817449 ,
         0.1967657 ,  0.20847025],
       [ 0.61699675,  0.35169442,  0.31139755,  1.        ,  0.28824128,
         0.61572901,  0.0870044 ],
       [ 0.30879332, -0.17248357,  0.0817449 ,  0.28824128,  1.        ,
         0.30828794, -0.15481097],
       [ 0.77359164, -0.14770154,  0.1967657 ,  0.61572901,  0.30828794,
         1.        , -0.04029313],
       [-0.06014372,  0.23398569,  0.20847025,  0.0870044 , -0.15481097,
        -0.04029313,  1.        ]])

In [15]:
portfolio_volatility = (portfolio_variances.dot(corr_matrix)).dot(portfolio_variances.T)**0.5
portfolio_volatility

0.2487607751921387

If this content is helpful and you want to make a donation please click on the button

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=29CVY97MEQ9BY)